export type LanguageArtsMixed10QuestionType = "reading" | "vocabulary" | "grammar" | "writing"

export interface LanguageArtsMixed10Question {
  id: number
  type: LanguageArtsMixed10QuestionType
  skill: string
  question: string
  options: string[]
  correctAnswer: number
  explanation: string
}

export const languageArtsMixed10Passage = `The Signal from Blue Mountain View

At Blue Mountain View Primary, rain was usually welcome. It cooled the dusty football field and filled the tanks beside the school garden. But during one October week, it fell without pause. By Thursday morning, the narrow river below the district had turned brown and restless.

Twelve-year-old Talia noticed that water had covered the lowest stepping-stone on her walk to school. Her grandfather, Mr. Bennett, had taught her to observe the river carefully. “One covered stone may mean little,” he often said, “but several changes together can tell a story.” Talia photographed the river from the footbridge and continued uphill.

In science class, Mr. Brown asked the students to record the week's weather. Talia showed him her photograph and compared it with one she had taken on Tuesday. The water had risen noticeably. Classmate Rohan pointed out another change: tiny streams were racing down slopes that were normally dry. Their class weather gauge also showed that nearly twice as much rain had fallen as on an ordinary wet day.

The students did not announce that a flood was coming. Mr. Brown reminded them that one class could not make an official warning. Instead, they organised their evidence. One group checked the rain measurements. Another marked safe footpaths on a district map. Talia and Rohan wrote a brief report for Principal Campbell, who telephoned the parish disaster coordinator.

The coordinator thanked the class but explained that measurements from higher in the hills were also needed. A volunteer checked those gauges and reported even heavier rainfall. The coordinator then advised families near the river to move animals, important papers, and small appliances to higher places. She also asked residents to use the main road instead of the footbridge.

Some neighbours acted immediately, while others thought the river would settle as it had before. Mr. Bennett did not argue with them. He calmly helped an elderly neighbour carry two boxes uphill, then returned for her radio and medicine. Seeing his quiet preparation, two doubtful families began moving their belongings too.

That night, the river spilled across the footpath and entered three low yards. No one was injured, and most valuable belongings had already been moved. By morning, the rain had eased. The students were proud, but Principal Campbell praised them for something more important than being correct: they had observed carefully, checked their information, and passed it to people trained to make decisions.

The following month, the school started a community weather club. Students still studied clouds and rainfall, but they also learnt a lasting lesson. Useful information becomes most powerful when people test it, share it responsibly, and use it to care for one another.`

export const languageArtsMixed10Questions: LanguageArtsMixed10Question[] = [
  {id:1,type:"reading",skill:"Main Idea",question:"What is the main idea of the passage?",options:["Students use checked weather evidence responsibly to help their community prepare for danger.","A grandfather persuades reluctant neighbours to leave their homes during a dangerous flood.","A disaster coordinator teaches a school how to measure rainfall in a mountain district.","Residents discover that the footbridge is less reliable than the district's main road."],correctAnswer:0,explanation:"The passage centres on the students observing changes, checking evidence, and sharing it through the proper channels so the community can prepare. The other options focus on one person, one official, or one route rather than the whole passage."},
  {id:2,type:"reading",skill:"Supporting Evidence",question:"Which detail BEST shows that the students checked their information before reporting it?",options:["They compared photographs, verified rain measurements, and organised the evidence.","They walked uphill after seeing water cover the lowest stepping-stone.","They learnt that several families had begun moving their belongings.","They heard that the river entered three low yards during the night."],correctAnswer:0,explanation:"Comparing photographs and verifying measurements directly shows the students testing their observations. The other details describe travel, residents' actions, or the later flood, not evidence-checking."},
  {id:3,type:"reading",skill:"Sequence",question:"What happened immediately after Principal Campbell received the students' report?",options:["She telephoned the parish disaster coordinator.","A volunteer checked gauges higher in the hills.","Families moved important belongings uphill.","The river spilled across the footpath."],correctAnswer:0,explanation:"The passage states that Principal Campbell telephoned the coordinator after receiving the report. The gauge check, preparations, and flooding all occurred later."},
  {id:4,type:"reading",skill:"Cause and Effect",question:"Why did the disaster coordinator seek measurements from higher in the hills?",options:["She needed wider evidence before advising the community.","She wanted students to stop using their weather gauge.","She believed the school photograph had been taken on Tuesday.","She planned to replace the footbridge with a safer crossing."],correctAnswer:0,explanation:"The coordinator needed information from another location before acting, which strengthened the evidence. Nothing suggests that she distrusted the students' gauge, confused the date, or planned construction."},
  {id:5,type:"reading",skill:"Character Trait",question:"Which trait does Talia show most clearly?",options:["Observant, because she notices and compares changes in the river.","Competitive, because she wants her report to be chosen over Rohan's.","Impatient, because she announces a warning before adults respond.","Secretive, because she hides the photograph from her classmates."],correctAnswer:0,explanation:"Talia notices the covered stone, photographs the river, and compares changes. The passage does not show rivalry, a premature warning, or secrecy."},
  {id:6,type:"reading",skill:"Inference",question:"What can the reader infer about Mr. Bennett's influence on the neighbours?",options:["His calm actions made preparation seem sensible to doubtful families.","His argument convinced every family that the river would overflow.","His official position required residents to follow his instructions.","His weather measurements replaced the coordinator's missing evidence."],correctAnswer:0,explanation:"Two doubtful families act after watching Mr. Bennett quietly help someone prepare, so his example influences them. He does not argue, hold official authority, or supply measurements."},
  {id:7,type:"reading",skill:"Vocabulary in Context",question:"What does “settle” mean in the sentence “the river would settle as it had before”?",options:["Return to a calmer, lower level","Carry soil into nearby yards","Change direction near the bridge","Become clearer after the rain"],correctAnswer:0,explanation:"The neighbours expect the rising river to calm and lower, as it had on earlier occasions. The surrounding sentences do not refer to soil, direction, or water clarity."},
  {id:8,type:"reading",skill:"Author's Purpose",question:"What is the author's main purpose?",options:["To show how careful observation and responsible action can protect a community","To explain every step used by officials to predict floods accurately","To persuade readers that mountain districts should close their footbridges","To entertain readers with an argument between students and their neighbours"],correctAnswer:0,explanation:"The narrative demonstrates a principle: information helps when it is checked, shared responsibly, and used with care. It is not a technical manual, a campaign against bridges, or a story about an argument."},
  {id:9,type:"reading",skill:"Problem and Solution",question:"Which statement BEST describes the central problem and response?",options:["Signs of possible flooding appear, so students gather evidence and alert responsible adults.","The school lacks rainfall records, so the coordinator provides a new weather gauge.","Several neighbours refuse to move, so Mr. Bennett orders them to leave immediately.","The footbridge becomes damaged, so residents build a safer route before nightfall."],correctAnswer:0,explanation:"The rising river and heavy rain create the risk; the students respond by checking evidence and reporting it. The other choices invent a donated gauge, an order, or bridge construction."},
  {id:10,type:"reading",skill:"Comparison and Contrast",question:"How did some neighbours' first response differ from Mr. Bennett's?",options:["They expected the river to settle, while he began preparing calmly.","They moved their animals first, while he waited for an official warning.","They checked the hill gauges, while he photographed the footbridge.","They used the main road, while he continued crossing the footbridge."],correctAnswer:0,explanation:"Some neighbours doubted the need to act, while Mr. Bennett quietly helped move important items. The remaining comparisons assign actions to the wrong people or are unsupported."},
  {id:11,type:"reading",skill:"Drawing Conclusions",question:"Why did Principal Campbell praise how the students worked rather than simply saying they predicted the flood?",options:["Their responsible process was valuable even before the outcome was known.","Their prediction mattered only because three yards were eventually flooded.","Their report contained all the information the coordinator would ever need.","Their class had authority to issue warnings without consulting officials."],correctAnswer:0,explanation:"Careful observation, verification, and responsible reporting are sound practices whether or not flooding follows. The passage rejects the ideas that the outcome alone mattered, the report was complete, or the class had warning authority."},
  {id:12,type:"reading",skill:"Theme",question:"Which theme is BEST supported by the passage?",options:["Knowledge serves people best when it is tested and shared responsibly.","Young people should solve community emergencies without adult assistance.","People who doubt a warning usually prevent others from taking action.","Natural dangers can always be avoided when rainfall is measured correctly."],correctAnswer:0,explanation:"The closing lesson and the students' actions support responsible use of tested information. Adults remain important, doubters later prepare, and measurement cannot prevent all natural danger."},
  {id:13,type:"reading",skill:"Interpreting Details",question:"Why does the passage mention the covered stepping-stone, dry slopes carrying streams, and unusual rain total?",options:["Together, they show several signs that conditions were becoming risky.","Together, they prove that the footbridge had already become unsafe.","Together, they explain why the school garden needed additional water.","Together, they show that the students travelled by different routes."],correctAnswer:0,explanation:"The details combine into a pattern of rising water and heavy runoff. They do not prove bridge damage, concern the garden's needs, or describe different journeys."},
  {id:14,type:"reading",skill:"Fact and Opinion",question:"Which statement is an OPINION?",options:["The weather club was the school's most valuable project.","The river entered three low yards during the night.","A volunteer checked gauges higher in the hills.","The school began a weather club the following month."],correctAnswer:0,explanation:"Calling the club the most valuable project is a judgement that cannot be proved from the passage. The other statements are specific events reported in the text."},
  {id:15,type:"reading",skill:"Summary",question:"Which is the BEST summary of the passage?",options:["Students notice flood signs, verify and report them, and help their community prepare while learning to use information responsibly.","Talia photographs a river, and her grandfather later moves a neighbour's radio and medicine away from the water.","A coordinator studies rainfall in the hills before telling all residents to abandon their homes and cross by the main road.","Heavy rain fills school tanks, damages a footbridge, and leads students to begin a club that studies clouds."],correctAnswer:0,explanation:"The first option includes the warning signs, the students' responsible process, the community response, and the lasting lesson. The others omit central ideas or add events that did not occur."},
  {id:16,type:"vocabulary",skill:"Synonym",question:"Which word is closest in meaning to “brief” in “a brief report”?",options:["concise","private","urgent","formal"],correctAnswer:0,explanation:"A brief report is short and concise. Private concerns access, urgent concerns time, and formal concerns style."},
  {id:17,type:"vocabulary",skill:"Antonym",question:"Which word is an ANTONYM for “narrow”?",options:["broad","steep","shallow","distant"],correctAnswer:0,explanation:"Broad means wide and is the opposite of narrow. The other words describe slope, depth, or distance."},
  {id:18,type:"vocabulary",skill:"Prefix",question:"What does the prefix “re-” mean in “returned”?",options:["again or back","before or earlier","wrongly or badly","below or beneath"],correctAnswer:0,explanation:"Re- means again or back; returned means came back. The other meanings belong to different prefixes."},
  {id:19,type:"vocabulary",skill:"Suffix",question:"What does the suffix “-ful” mean in the word “useful”?",options:["full of","without","able to be","one who"],correctAnswer:0,explanation:"The suffix -ful means full of or having; useful describes something having use or value. The other meanings match suffixes such as -less, -able, or -er."},
  {id:20,type:"vocabulary",skill:"Connotation",question:"Which word gives the MOST positive impression of how the students handled the evidence?",options:["carefully","slowly","quietly","formally"],correctAnswer:0,explanation:"Carefully suggests accuracy and responsible attention. The other words describe pace, sound, or manner without the same positive judgement."},
  {id:21,type:"vocabulary",skill:"Multiple Meaning",question:"Which sentence uses “gauge” with the SAME meaning as in the passage?",options:["The mechanic checked the fuel gauge.","The coach tried to gauge our confidence.","We could not gauge how long the trip felt.","The teacher will gauge interest by asking questions."],correctAnswer:0,explanation:"In both the passage and the first sentence, gauge is a measuring instrument. In the other sentences, gauge is a verb meaning estimate or judge."},
  {id:22,type:"vocabulary",skill:"Context Clues",question:"The river was described as “restless” because it was brown, rising, and moving strongly. What does “restless” suggest here?",options:["active and unsettled","silent and hidden","shallow and clear","steady and controlled"],correctAnswer:0,explanation:"The clues show disturbed, active water, so restless means active and unsettled. The other descriptions conflict with the rising, forceful river."},
  {id:23,type:"vocabulary",skill:"Denotation",question:"Which meaning is the DENOTATION of “evidence”?",options:["information that helps prove whether something is true","a warning that causes people to become frightened","an opinion offered by someone with experience","a plan created to solve a future problem"],correctAnswer:0,explanation:"Denotation is a word's direct dictionary meaning. Evidence is information used to support or test a claim; it is not itself a warning, opinion, or plan."},
  {id:24,type:"vocabulary",skill:"Figurative Language",question:"What does Mr. Bennett mean when he says several changes “can tell a story”?",options:["The changes can reveal what may be happening.","The changes can speak aloud to careful listeners.","The changes can entertain people during bad weather.","The changes can record events without human help."],correctAnswer:0,explanation:"The phrase personifies the signs to mean that together they reveal a developing situation. The remaining options interpret the words too literally or change their purpose."},
  {id:25,type:"vocabulary",skill:"Word Relationship",question:"Which pair has the same relationship as “observe : notice”?",options:["verify : confirm","prepare : delay","advise : ignore","protect : endanger"],correctAnswer:0,explanation:"Observe and notice have similar meanings, just as verify and confirm do. The other pairs express contrast rather than similarity."},
  {id:26,type:"grammar",skill:"Subject–Verb Agreement",question:"Which sentence has correct subject–verb agreement?",options:["The set of photographs shows how the river changed.","The set of photographs show how the river changed.","The set of photographs have shown how the river changed.","The set of photographs were showing how the river changed."],correctAnswer:0,explanation:"The subject set is singular, so it takes the singular verb shows. Photographs is part of a prepositional phrase and does not control the verb."},
  {id:27,type:"grammar",skill:"Verb Tense",question:"Which sentence correctly shows that one action happened before another past action?",options:["The students had checked the figures before they submitted the report.","The students check the figures before they submitted the report.","The students will check the figures before they submitted the report.","The students are checking the figures before they submitted the report."],correctAnswer:0,explanation:"Had checked is past perfect and clearly places the checking before the past action submitted. The other choices mix incompatible verb tenses."},
  {id:28,type:"grammar",skill:"Pronoun Agreement",question:"Which sentence uses pronouns correctly?",options:["Talia and Rohan presented their report to the principal.","Talia and Rohan presented her report to the principal.","Talia presented their report that she wrote alone.","Rohan presented our report that he wrote alone."],correctAnswer:0,explanation:"The plural pronoun their agrees with the compound subject Talia and Rohan. The other pronouns conflict with the stated singular or plural antecedents."},
  {id:29,type:"grammar",skill:"Comma Use",question:"Which sentence uses commas correctly?",options:["The students checked rainfall, mapped paths, and wrote a report.","The students checked, rainfall mapped paths and wrote a report.","The students checked rainfall mapped, paths, and wrote a report.","The students, checked rainfall mapped paths and, wrote a report."],correctAnswer:0,explanation:"Commas correctly separate the three actions in a series. The other options omit needed separators or place commas between words that belong together."},
  {id:30,type:"grammar",skill:"Apostrophe",question:"Which sentence uses an apostrophe correctly?",options:["The neighbours' belongings were moved uphill.","The neighbours belongings were moved uphill.","The neighbour's belongings were moved for all families.","The neighbours's belongings were moved uphill."],correctAnswer:0,explanation:"Neighbours' is the possessive form of the plural noun neighbours. The other options omit the apostrophe or use a singular or nonstandard possessive form."},
  {id:31,type:"grammar",skill:"Conjunction",question:"Choose the best conjunction: “The class could not issue a warning, ___ it reported the evidence to the principal.”",options:["so","unless","because","although"],correctAnswer:0,explanation:"So correctly shows the result of the class lacking authority: it passed the evidence to a responsible adult. The other conjunctions create the wrong logical relationship."},
  {id:32,type:"grammar",skill:"Parts of Speech",question:"Which word is the adverb in “Mr. Bennett calmly carried the boxes uphill”?",options:["calmly","carried","boxes","Mr. Bennett"],correctAnswer:0,explanation:"Calmly describes how he carried the boxes, so it is an adverb. Carried is a verb, boxes is a noun, and Mr. Bennett is a proper noun."},
  {id:33,type:"grammar",skill:"Sentence Structure",question:"Which option is a complete sentence?",options:["The rain eased before the students returned to school.","Because the rain eased before morning.","While the students returning to school.","The rain easing before the students returned."],correctAnswer:0,explanation:"The first option contains a complete independent clause. The others are a dependent clause or fragments lacking a properly formed main clause."},
  {id:34,type:"grammar",skill:"Capitalisation",question:"Which sentence uses capital letters correctly?",options:["Principal Campbell called the parish disaster coordinator on Thursday.","principal Campbell called the Parish disaster coordinator on Thursday.","Principal campbell called the parish Disaster Coordinator on thursday.","Principal Campbell called the Parish Disaster coordinator on Thursday."],correctAnswer:0,explanation:"The title before a name, the surname, and Thursday are capitalised; the general job phrase parish disaster coordinator is not. The other options misuse capitals."},
  {id:35,type:"grammar",skill:"Sentence Correction",question:"Which revision corrects “The students was proud because their work help the district”?",options:["The students were proud because their work helped the district.","The students was proud because their work helped the district.","The students were proudly because their work help the district.","The students were proud because their work helping the district."],correctAnswer:0,explanation:"Were agrees with students, and helped correctly states the completed action. Each distractor retains an agreement, word-form, or verb-form error."},
  {id:36,type:"writing",skill:"Organisation",question:"A student is writing a paragraph about the class response. Which order is most logical?",options:["Notice the signs; check the evidence; report to the principal; reflect on the outcome.","Reflect on the outcome; report to the principal; notice the signs; check the evidence.","Report to the principal; notice the signs; reflect on the outcome; check the evidence.","Check the evidence; reflect on the outcome; report to the principal; notice the signs."],correctAnswer:0,explanation:"The first order follows the actual and logical process from observation through verification and reporting to reflection. The other sequences place consequences or reporting before their causes."},
  {id:37,type:"writing",skill:"Purpose and Audience",question:"Which opening is MOST suitable for a safety report to the principal?",options:["Our measurements show unusual rainfall and a rising river near the footbridge.","You would not believe the absolutely terrifying river we saw today!","I am writing because weather is a topic that many people find interesting.","Once upon a time, a restless river rushed below our quiet little school."],correctAnswer:0,explanation:"A safety report needs a direct, factual opening that identifies the concern and evidence. The other openings are exaggerated, vague, or suited to a story rather than a report."},
  {id:38,type:"writing",skill:"Supporting Evidence",question:"Which detail BEST supports the claim that rainfall was unusually heavy?",options:["The gauge recorded nearly twice the amount of an ordinary wet day.","The school garden had water tanks beside the dusty football field.","The students studied clouds when they joined the weather club.","The principal praised the class after the rain had finally eased."],correctAnswer:0,explanation:"The comparison from the gauge directly measures how unusual the rainfall was. The other details concern the setting, later club activities, or praise rather than rainfall amount."},
  {id:39,type:"writing",skill:"Transition",question:"Choose the best transition: “The first photograph showed rising water. ___, the rain gauge confirmed unusually heavy rainfall.”",options:["In addition","For example","On the contrary","In conclusion"],correctAnswer:0,explanation:"In addition introduces another supporting piece of evidence. For example would make the gauge an example of the photograph, while the other transitions signal opposition or a conclusion."},
  {id:40,type:"writing",skill:"Revision for Clarity",question:"Which revision is clearest? “They told them about it after they checked it.”",options:["The students told Principal Campbell about the flood signs after checking their evidence.","After checking it, they told Principal Campbell about the things they had noticed.","The students told her about it after the information had been checked by them.","After they checked the signs and it, they told the principal about the matter."],correctAnswer:0,explanation:"The first revision replaces every unclear pronoun with a precise person, concern, or action. The other choices leave vague pronouns, use unnecessary passive wording, or create a confusing object."},
]
