"use client"

import { useCallback, useEffect, useRef, useState } from "react"
import Link from "next/link"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { useAuth } from "@/contexts/auth-context"
import { saveStudentTestResult } from "@/lib/student-test-results"
import { prepareAssessment, preparePreview } from "@/lib/assessment-engine"
import { ArrowLeft, BookOpen, CheckCircle, ChevronLeft, ChevronRight, Clock, Crown, Flag, Home, Lock, Printer, RotateCcw, XCircle } from "lucide-react"
import { cn } from "@/lib/utils"

const FREE_QUESTION_LIMIT = 5

type QuestionType = "reading" | "vocabulary" | "grammar" | "writing"
interface Question { id:number; type:QuestionType; skill:string; question:string; options:string[]; correctAnswer:number; explanation:string }

const PASSAGE = `When the roof of Harbour View Primary's library began leaking, many people assumed the room would remain closed for months. The school had little money for repairs, and several shelves had already been moved into a narrow storeroom. Grade 5 students were disappointed because the library was where they researched projects, borrowed storybooks, and met for the reading club.

Their teacher, Mr. Campbell, challenged them to think beyond the immediate problem. Instead of asking only how to repair the roof, he asked how the library could become more useful and less costly to operate. The students surveyed classmates, counted the hours of sunlight reaching the building, and interviewed a local electrician. They discovered that the roof received strong sunlight for most of the day and that the library's electricity bill was unusually high because lights and fans were often needed.

The class proposed the Bright Library Project. Their plan included repairing the roof, installing a small solar-energy system, improving ventilation, and creating a reading corner from reused materials. To gain support, they prepared charts showing the possible savings and explained how solar panels turn sunlight into electricity. A parents' group organised a fund-raising fair, a building supplier donated roofing sheets, and a renewable-energy company offered two solar panels at a reduced price.

Work began during the mid-term break. Adults handled the dangerous tasks, while students cleaned books, painted signs, and recorded each stage of the project. One unexpected problem arose when heavy clouds reduced the amount of solar power produced during testing. The electrician explained that the system included a battery, which stored energy collected during sunnier hours. This allowed the lights to operate even when the sky was overcast.

When the library reopened, it was cooler, brighter, and more welcoming. The solar system did not provide all the building's electricity, but it lowered the school's monthly costs. The reading club also attracted new members because the students had helped design the space. Most importantly, the project taught the class that solving one problem can create an opportunity to improve several things at once. Careful research, cooperation, and practical creativity had transformed a leaking room into a model for the school community.`

const QUESTIONS: Question[] = [
{id:1,type:"reading",skill:"Main Idea",question:"What is the passage mainly about?",options:["Students and adults improved a damaged library through research and teamwork.","A school replaced its entire library with a new computer laboratory.","Parents organised a fair mainly to buy books for younger children.","An electrician taught a class how to build solar panels from scratch."],correctAnswer:0,explanation:"The passage follows the research, planning, repair, and improvement of the school library."},
{id:2,type:"reading",skill:"Problem and Solution",question:"Which problem first led the class to begin the project?",options:["The reading club had too many members for the available books.","The library roof leaked and the school had little money for repairs.","The solar panels stopped working during a long period of rain.","The school wanted to move the library into a larger building."],correctAnswer:1,explanation:"The leaking roof and limited repair funds created the original problem."},
{id:3,type:"reading",skill:"Inference",question:"Why did Mr. Campbell ask students to think beyond repairing the roof?",options:["He wanted them to postpone repairs until the following school year.","He believed the library should become a classroom for electricians.","He wanted the solution to improve the library in several ways.","He hoped students would decide that the library was unnecessary."],correctAnswer:2,explanation:"He encouraged them to consider usefulness, cost, ventilation, and learning space."},
{id:4,type:"reading",skill:"Cause and Effect",question:"Why did the class consider using solar energy?",options:["The parents' group requested a project involving new technology.","The building supplier could not donate enough roofing sheets.","The students wanted the library to remain open throughout the night.","The roof received strong sunlight and electricity costs were high."],correctAnswer:3,explanation:"Those conditions made solar energy a practical part of the plan."},
{id:5,type:"reading",skill:"Sequence",question:"Which event happened first?",options:["Students surveyed classmates and studied the building's sunlight.","The parents' group held a fund-raising fair for the project.","Adults repaired the roof during the mid-term break.","The reopened library attracted new reading-club members."],correctAnswer:0,explanation:"The research stage came before fundraising, construction, and reopening."},
{id:6,type:"reading",skill:"Detail",question:"What did the students do during the repair work?",options:["They installed the roofing sheets and connected the electrical system.","They cleaned books, painted signs, and recorded the project's stages.","They tested the battery and repaired the library's ventilation system.","They negotiated the price of the solar panels with the company."],correctAnswer:1,explanation:"The passage lists those safe, student-appropriate tasks."},
{id:7,type:"reading",skill:"Author's Purpose",question:"Why does the author mention that adults handled dangerous tasks?",options:["To suggest that the students made no useful contribution.","To explain why the project took longer than first expected.","To show that responsibilities were shared with attention to safety.","To prove that only adults understood the purpose of the project."],correctAnswer:2,explanation:"The detail shows cooperation while making safety clear."},
{id:8,type:"reading",skill:"Problem and Solution",question:"How did the system provide light when the sky was cloudy?",options:["The students opened extra windows to bring in more daylight.","The school borrowed electricity from a nearby classroom.","The electrician added another solar panel during testing.","A battery stored energy collected during sunnier periods."],correctAnswer:3,explanation:"Stored energy allowed the lights to work during overcast conditions."},
{id:9,type:"reading",skill:"Vocabulary in Context",question:"What does “overcast” most nearly mean in the passage?",options:["Covered with clouds and receiving little direct sunlight.","Dark because all the electric lights had stopped working.","Cool because improved ventilation moved air through the room.","Busy because many students had entered the reopened library."],correctAnswer:0,explanation:"The sentence links overcast conditions with heavy clouds."},
{id:10,type:"reading",skill:"Evidence",question:"Which detail best shows that the project produced an ongoing financial benefit?",options:["The students prepared charts to explain possible savings.","The solar system lowered the school's monthly electricity costs.","A supplier donated roofing sheets for the repair work.","The parents' group raised money at a community fair."],correctAnswer:1,explanation:"Lower monthly bills are a continuing financial benefit."},
{id:11,type:"reading",skill:"Theme",question:"Which lesson is best supported by the passage?",options:["Technology can solve every problem without human effort.","School projects succeed only when companies provide money.","Research and cooperation can turn one problem into wider improvement.","Students should leave difficult decisions entirely to adults."],correctAnswer:2,explanation:"The project combined careful study, shared effort, and practical creativity."},
{id:12,type:"reading",skill:"Text Structure",question:"How is the passage mainly organised?",options:["As a comparison of solar power with several other energy sources.","As instructions for repairing a roof and wiring a school building.","As a description of different rooms in Harbour View Primary.","As a problem, a researched plan, an obstacle, and the final results."],correctAnswer:3,explanation:"The passage progresses from the leak to planning, implementation, challenge, and outcome."},
{id:13,type:"reading",skill:"Inference",question:"What can the reader infer about the students after the library reopened?",options:["They likely felt proud because they helped shape the improved space.","They probably regretted using reused materials in the reading corner.","They expected the solar system to power the entire school building.","They preferred the old library because it required less responsibility."],correctAnswer:0,explanation:"Their involvement and the growth of the reading club suggest ownership and pride."},
{id:14,type:"reading",skill:"Reference",question:"In the sentence “This allowed the lights to operate,” what does “This” refer to?",options:["The clouds reducing the solar energy produced during testing.","The battery storing energy collected during sunnier hours.","The students recording each stage of the repair project.","The adults completing dangerous tasks during the break."],correctAnswer:1,explanation:"The immediately preceding idea is the battery storing energy."},
{id:15,type:"reading",skill:"Summary",question:"Which sentence best summarises the passage?",options:["A school closed its library because repairs and electricity were too costly.","A company donated panels and completed every part of a school project.","Students researched and helped carry out a plan that repaired and improved their library.","A reading club raised money to replace books damaged by a leaking roof."],correctAnswer:2,explanation:"It captures the problem, research, action, and broader improvement."},
{id:16,type:"vocabulary",skill:"Synonym",question:"Which word is closest in meaning to “welcoming” as used in the passage?",options:["Inviting","Crowded","Costly","Temporary"],correctAnswer:0,explanation:"Welcoming means pleasant and inviting."},
{id:17,type:"vocabulary",skill:"Antonym",question:"Which word is the best antonym for “reduced”?",options:["Measured","Increased","Stored","Recorded"],correctAnswer:1,explanation:"Increased is the opposite of reduced."},
{id:18,type:"vocabulary",skill:"Context Clues",question:"What does “operate” mean in “the lights could operate”?",options:["To be repaired by a trained electrician.","To be moved from one room to another.","To work or function as intended.","To use more energy than usual."],correctAnswer:2,explanation:"Operate means work or function."},
{id:19,type:"vocabulary",skill:"Prefix",question:"What does the prefix “re-” mean in “reopened”?",options:["Below","Before","Without","Again"],correctAnswer:3,explanation:"Reopened means opened again."},
{id:20,type:"vocabulary",skill:"Multiple Meaning",question:"Which sentence uses “current” to mean a flow of electricity?",options:["The current passed safely through the wire.","Her current project is about renewable energy.","They discussed current events during class.","The river's current became stronger after rain."],correctAnswer:0,explanation:"Here current refers to electrical flow."},
{id:21,type:"vocabulary",skill:"Suffix",question:"What does the suffix “-ful” mean in “useful”?",options:["Without","Full of","Before","Small"],correctAnswer:1,explanation:"Useful means full of use or benefit."},
{id:22,type:"vocabulary",skill:"Figurative Language",question:"Which sentence contains personification?",options:["The sunlight entered through the wide windows.","The panels rested securely on the repaired roof.","The cheerful library welcomed readers each morning.","The students arranged books on the lower shelves."],correctAnswer:2,explanation:"The library is given the human action of welcoming."},
{id:23,type:"vocabulary",skill:"Connotation",question:"Which word has the most positive connotation?",options:["Unusual","Expensive","Ordinary","Innovative"],correctAnswer:3,explanation:"Innovative suggests useful creativity and new thinking."},
{id:24,type:"vocabulary",skill:"Idiom",question:"What does the expression “lend a hand” mean?",options:["Offer help with a task.","Borrow something for a while.","Point toward a nearby place.","Write down a set of instructions."],correctAnswer:0,explanation:"The idiom means to help."},
{id:25,type:"vocabulary",skill:"Word Relationship",question:"Solar panel is to solar system as page is to ____.",options:["Shelf","Book","Reader","Pencil"],correctAnswer:1,explanation:"A panel is part of a solar system, just as a page is part of a book."},
{id:26,type:"grammar",skill:"Subject-Verb Agreement",question:"Which sentence is correct?",options:["The students studies the sunlight each day.","The students was studying the sunlight each day.","The students study the sunlight each day.","The students has studied the sunlight each day."],correctAnswer:2,explanation:"The plural subject students takes the plural verb study."},
{id:27,type:"grammar",skill:"Verb Tense",question:"Which sentence is correctly written in the past tense?",options:["The class plans the project during the break.","The class will plan the project during the break.","The class is planning the project during the break.","The class planned the project during the break."],correctAnswer:3,explanation:"Planned is the correct past-tense form."},
{id:28,type:"grammar",skill:"Pronouns",question:"Choose the correct pronoun: “The electrician explained the battery to Maya and ___.”",options:["me","I","mine","my"],correctAnswer:0,explanation:"The object pronoun me follows the preposition to."},
{id:29,type:"grammar",skill:"Adjectives",question:"Which word is the adjective in “The bright library welcomed eager readers”?",options:["welcomed","bright","library","readers"],correctAnswer:1,explanation:"Bright describes the noun library."},
{id:30,type:"grammar",skill:"Adverbs",question:"Which word is the adverb in “The students carefully cleaned the books”?",options:["students","books","carefully","cleaned"],correctAnswer:2,explanation:"Carefully tells how the students cleaned."},
{id:31,type:"grammar",skill:"Conjunctions",question:"Choose the best conjunction: “The sky was cloudy, ___ the battery kept the lights on.”",options:["because","unless","so","but"],correctAnswer:3,explanation:"But shows contrast between the cloudy sky and the working lights."},
{id:32,type:"grammar",skill:"Punctuation",question:"Which sentence is punctuated correctly?",options:["Mr. Campbell said, “Let us begin the research.”","Mr. Campbell said “Let us begin the research”.","Mr. Campbell, said, “Let us begin the research.”","Mr. Campbell said, Let us begin the research."],correctAnswer:0,explanation:"The comma, quotation marks, and final punctuation are correctly placed."},
{id:33,type:"grammar",skill:"Possessive Nouns",question:"Which phrase correctly shows that the library belongs to one school?",options:["the schools library","the school's library","the schools' library","the school library's"],correctAnswer:1,explanation:"School's is the singular possessive form."},
{id:34,type:"grammar",skill:"Sentence Types",question:"Which is a compound sentence?",options:["Because the roof leaked during the heavy rain.","The newly repaired roof above the reading corner.","The roof was repaired, and the library reopened.","Repairing the roof during the mid-term break."],correctAnswer:2,explanation:"It joins two independent clauses with the conjunction and."},
{id:35,type:"grammar",skill:"Capitalisation",question:"Which sentence uses capital letters correctly?",options:["harbour View Primary reopened its library.","Harbour view primary reopened its library.","Harbour View primary reopened its Library.","Harbour View Primary reopened its library."],correctAnswer:3,explanation:"All words in the proper school name are capitalised."},
{id:36,type:"writing",skill:"Topic Sentence",question:"Which is the strongest topic sentence for a paragraph about reducing electricity use?",options:["Schools can lower electricity use through simple and responsible habits.","Schools use electricity for lights, fans, computers, and other equipment.","Some school buildings receive more natural light than other buildings.","Students may notice that certain rooms feel warmer during the afternoon."],correctAnswer:0,explanation:"It presents a clear controlling idea that can be developed with supporting details."},
{id:37,type:"writing",skill:"Supporting Detail",question:"Which detail best supports the claim that the improved library encouraged reading?",options:["The repaired roof used sheets donated by a building supplier.","The reading club attracted new members after the library reopened.","The electrician explained how the battery stored solar energy.","The students painted signs during the mid-term repair work."],correctAnswer:1,explanation:"The increase in reading-club membership directly supports the claim."},
{id:38,type:"writing",skill:"Transitions",question:"Choose the best transition: “The school repaired the roof. ___, it installed solar panels.”",options:["Instead","For example","In addition","Otherwise"],correctAnswer:2,explanation:"In addition introduces another improvement."},
{id:39,type:"writing",skill:"Organisation",question:"Which sentence does NOT belong in a paragraph about improving a library?",options:["Comfortable seating can make reading more enjoyable.","Suitable lighting helps readers see the pages clearly.","Clearly labelled shelves make books easier to locate.","The library displays photographs from previous school events near its entrance."],correctAnswer:3,explanation:"The photograph display belongs in the library setting, but it does not support the paragraph’s focus on changes that improve the library for reading and learning."},
{id:40,type:"writing",skill:"Conclusion",question:"Which is the strongest conclusion for an essay about community cooperation?",options:["Communities include people with many different abilities and responsibilities.","Some projects require more time and planning than people first expect.","People often meet in groups when they need to discuss shared concerns.","Working together can turn shared ideas into lasting community improvements."],correctAnswer:3,explanation:"It restates the central idea and leaves a meaningful final thought."}
]

const sectionLabel=(t:QuestionType)=>t==="reading"?"Reading Comprehension":t==="vocabulary"?"Vocabulary & Word Study":t==="grammar"?"Grammar & Language Use":"Writing Skills"

export default function G5LaMix7MockTest(){
  const {isPremium,user}=useAuth()
  const source=isPremium?QUESTIONS:QUESTIONS.slice(0,FREE_QUESTION_LIMIT)
  const [started,setStarted]=useState(false),[showResults,setShowResults]=useState(false),[current,setCurrent]=useState(0),[timeLeft,setTimeLeft]=useState(3600)
  const [questions,setQuestions]=useState<Question[]>([]),[answers,setAnswers]=useState<(number|null)[]>([])
  const saved=useRef(false)
  const total=questions.length||source.length
  const score=useCallback(()=>answers.reduce((sum,a,i)=>sum+(a===questions[i]?.correctAnswer?1:0),0),[answers,questions])
  const percentage=useCallback(()=>total?Math.round(score()*100/total):0,[score,total])

  useEffect(()=>{if(!started||showResults)return;const timer=setInterval(()=>setTimeLeft(v=>{if(v<=1){setShowResults(true);return 0}return v-1}),1000);return()=>clearInterval(timer)},[started,showResults])
  useEffect(()=>{if(!showResults||!user?.id||saved.current||!questions.length)return;saved.current=true;void saveStudentTestResult({parentId:user.id,studentName:user.childName??"Student",grade:"grade5",subject:"Literacy",testName:"Mixed 7",difficulty:"Mixed",score:score(),totalQuestions:questions.length,percentage:percentage(),completedAt:new Date().toISOString()}).catch(()=>{saved.current=false})},[showResults,user?.id,user?.childName,questions,answers,score,percentage])

  const startTest=()=>{const q=isPremium?prepareAssessment(QUESTIONS):preparePreview(QUESTIONS,FREE_QUESTION_LIMIT);setQuestions(q);setAnswers(Array(q.length).fill(null));setCurrent(0);setTimeLeft(3600);setShowResults(false);saved.current=false;setStarted(true)}
  const reset=()=>{setStarted(false);setShowResults(false);setQuestions([]);setAnswers([]);setCurrent(0);setTimeLeft(3600);saved.current=false}
  const formatTime=(s:number)=>`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`

  if(!started)return <div className="min-h-screen bg-gradient-to-b from-sky-50 to-slate-50"><Header/><main className="container mx-auto px-4 py-10"><Link href="/mock-tests/language-arts"><Button variant="ghost" className="mb-6"><ArrowLeft className="mr-2 h-4 w-4"/>Back to Language Arts Mock Tests</Button></Link><Card className="mx-auto max-w-3xl border-blue-200 shadow-lg"><CardHeader className="bg-blue-50 text-center"><BookOpen className="mx-auto mb-4 h-14 w-14 text-blue-600"/><CardTitle className="text-2xl text-blue-800">Language Arts Mixed 7</CardTitle><p className="text-slate-600">Grade 5 PEP Language Arts · Mixed Level Practice</p></CardHeader><CardContent className="space-y-6 p-6">{!isPremium&&<div className="rounded-lg border border-amber-200 bg-amber-50 p-4"><div className="flex items-start gap-3"><Lock className="mt-1 h-5 w-5 text-amber-600"/><div><p className="font-semibold text-amber-800">Free Preview Mode</p><p className="text-sm text-amber-700">Try {FREE_QUESTION_LIMIT} questions free. Upgrade to unlock all 40.</p><Link href="/pricing" className="mt-3 inline-block"><Button className="bg-amber-500 hover:bg-amber-600"><Crown className="mr-2 h-4 w-4"/>Upgrade to Premium</Button></Link></div></div></div>}<div className="rounded-lg border border-blue-200 bg-white p-4"><h3 className="mb-2 font-semibold text-slate-800">Mixed Level Overview</h3><p className="text-slate-700">This test blends easy, moderate, and challenging questions across reading, vocabulary, grammar, and writing — giving you a complete picture of your Grade 5 Language Arts skills.</p></div><div className="rounded-lg bg-sky-50 p-4"><h3 className="mb-2 font-semibold text-sky-800">What to Expect</h3><ul className="space-y-1 text-sm text-slate-700"><li>Reading: literal comprehension → inference → literary analysis</li><li>Vocabulary: word meaning → figurative language → nuanced connotation</li><li>Grammar: basic parts of speech → complex clauses and transformations</li><li>Writing: paragraph structure → persuasive technique → analytical writing</li></ul></div><div className="grid grid-cols-2 gap-4 text-center"><div className="rounded-lg bg-gray-50 p-4"><p className="text-2xl font-bold text-blue-600">{source.length}</p><p className="text-sm text-slate-600">Questions {!isPremium&&"(Preview)"}</p></div><div className="rounded-lg bg-gray-50 p-4"><p className="text-2xl font-bold text-blue-600">60</p><p className="text-sm text-slate-600">Minutes</p></div></div><Button onClick={startTest} className="w-full bg-blue-600 py-6 text-lg hover:bg-blue-700">Start Test</Button></CardContent></Card></main><Footer/></div>

  if(showResults){const sc=score(),pct=percentage();return <div className="min-h-screen bg-gradient-to-b from-sky-50 to-slate-50"><Header/><main className="container mx-auto px-4 py-10"><Card className="mx-auto max-w-5xl border-blue-200 shadow-lg"><CardHeader className="bg-blue-50 text-center"><CheckCircle className="mx-auto mb-3 h-12 w-12 text-blue-600"/><CardTitle className="text-2xl text-blue-800">Language Arts Mixed 7 Completed</CardTitle><p className="text-5xl font-bold text-blue-600">{pct}%</p><p>{sc} of {questions.length} correct</p></CardHeader><CardContent className="space-y-4 p-6">{questions.map((q,i)=>{const ok=answers[i]===q.correctAnswer;return <div key={q.id} className={cn("rounded-lg border-l-4 p-4",ok?"border-green-500 bg-green-50":"border-red-500 bg-red-50")}><div className="flex gap-3">{ok?<CheckCircle className="h-5 w-5 text-green-600"/>:<XCircle className="h-5 w-5 text-red-600"/>}<div><p className="font-semibold">Question {i+1}: {q.question}</p><p className="text-sm">Your answer: {answers[i]===null?"Not answered":q.options[answers[i]!]}</p>{!ok&&<p className="text-sm text-green-700">Correct answer: {q.options[q.correctAnswer]}</p>}<p className="text-sm text-slate-600">{q.explanation}</p></div></div></div>})}<div className="flex flex-col gap-3 sm:flex-row"><Button onClick={reset}><RotateCcw className="mr-2 h-4 w-4"/>Try Again</Button><Button variant="outline" onClick={()=>window.print()}><Printer className="mr-2 h-4 w-4"/>Print Results</Button><Link href="/mock-tests/language-arts"><Button variant="outline"><Home className="mr-2 h-4 w-4"/>More Tests</Button></Link></div></CardContent></Card></main><Footer/></div>}

  const q=questions[current],answered=answers.filter(a=>a!==null).length
  return <div className="min-h-screen bg-gradient-to-b from-sky-50 to-slate-50"><Header/><header className="sticky top-0 z-10 bg-blue-800 text-white"><div className="container mx-auto flex items-center justify-between px-4 py-4"><div><h1 className="font-bold">Language Arts Mixed 7</h1><p className="text-xs text-blue-100">Question {current+1} of {questions.length}</p></div><div className="flex items-center gap-2 rounded-lg bg-green-600 px-4 py-2 font-mono"><Clock className="h-5 w-5"/>{formatTime(timeLeft)}</div></div></header><main className="container mx-auto max-w-5xl px-4 py-6"><div className="mb-4"><div className="mb-2 flex justify-between text-sm text-slate-600"><span>{answered}/{questions.length} answered</span><span>{Math.round(answered*100/questions.length)}% complete</span></div><Progress value={answered*100/questions.length}/></div><Card><CardContent className="space-y-5 p-6">{q.type==="reading"&&<div className="max-h-80 overflow-y-auto whitespace-pre-line rounded-lg border bg-slate-50 p-4 text-sm leading-relaxed">{PASSAGE}</div>}<div><span className="text-sm font-semibold text-blue-700">{sectionLabel(q.type)} · {q.skill}</span><h2 className="mt-2 text-lg font-medium">{q.question}</h2></div><div className="space-y-3">{q.options.map((option,i)=><button key={i} onClick={()=>setAnswers(a=>a.map((v,k)=>k===current?i:v))} className={cn("flex w-full gap-3 rounded-lg border-2 p-4 text-left transition-all",answers[current]===i?"border-blue-600 bg-blue-50":"border-gray-200 bg-white hover:border-blue-300")}><span className="font-medium text-blue-700">{String.fromCharCode(65+i)}.</span><span>{option}</span></button>)}</div><div className="flex justify-between"><Button variant="outline" disabled={current===0} onClick={()=>setCurrent(c=>c-1)}><ChevronLeft className="mr-2 h-4 w-4"/>Previous</Button>{current===questions.length-1?<Button onClick={()=>setShowResults(true)} className="bg-green-600 hover:bg-green-700"><Flag className="mr-2 h-4 w-4"/>Submit Test</Button>:<Button onClick={()=>setCurrent(c=>c+1)}>Next<ChevronRight className="ml-2 h-4 w-4"/></Button>}</div></CardContent></Card></main><Footer/></div>
}
