"use client"

import { useCallback, useEffect, useRef, useState } from "react"
import Link from "next/link"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { useAuth } from "@/contexts/auth-context"
import { saveStudentTestResult } from "@/lib/student-test-results"
import { prepareAssessment, preparePreview } from "@/lib/assessment-engine"
import { ArrowLeft, BookOpen, CheckCircle, Clock, Crown, Flag, Home, Lock, Printer, RotateCcw } from "lucide-react"

const FREE_QUESTION_LIMIT = 5
const PASSAGE = "At Seaview Primary, students often complained that the school courtyard became unbearably hot by midday. The concrete reflected heat, the few benches offered no shade, and the dusty corner beside the fence was rarely used. During lunch, most children crowded beneath one narrow verandah.\n\nMrs. Morgan asked the Grade 5 class to investigate instead of simply complaining. The students measured temperatures in four parts of the courtyard, counted how many children used each space, and interviewed the school gardener. They discovered that the hottest area was also the least used. The gardener explained that trees could provide shade, but large roots might damage nearby drains.\n\nThe class designed the Cool Courtyard Project. Their plan included planting two small-rooted shade trees, building movable benches from treated pallets, and painting a section of the concrete with a pale outdoor coating that absorbed less heat. They prepared a budget, compared prices, and presented their proposal to the principal and parent-teacher association.\n\nThe project did not proceed exactly as planned. One supplier could not deliver the selected trees, so the students consulted the gardener again and chose another suitable species. Rain delayed the painting by a week, and one pallet was too damaged to use. Instead of abandoning the project, the team adjusted the schedule and found replacement materials.\n\nSix weeks later, the courtyard looked and felt different. The new trees were still young, but fabric shade sails provided temporary cover while they grew. Students began using the benches for reading, board games, and quiet conversation. Teachers also used the area for small-group lessons.\n\nThe temperature had not dropped everywhere, and the project had not solved every problem. However, the class learned that careful measurement, expert advice, and flexibility could turn an overlooked space into a useful one. Their work also showed that a good solution is not always a single object; sometimes it is a combination of small, well-planned changes."

type QuestionType = "reading" | "vocabulary" | "grammar" | "writing"
interface Question { id:number; type:QuestionType; skill:string; question:string; options:string[]; correctAnswer:number; explanation:string }

const QUESTIONS: Question[] = [
{id:1,type:"reading",skill:"Main Idea",question:"What is the passage mainly about?",options:["Students used research and teamwork to improve a hot school courtyard.","Teachers moved all lessons from classrooms into the courtyard.","The gardener planted a large forest beside the school drains.","Parents replaced the school verandah with a covered hall."],correctAnswer:0,explanation:"The passage follows the class as it investigated and improved the courtyard."},
{id:2,type:"reading",skill:"Problem and Solution",question:"What problem first led to the project?",options:["The courtyard was hot, poorly shaded, and not widely used.","The school had no place for teachers to hold meetings.","The gardener wanted to remove every tree from the property.","The parent-teacher association cancelled all outdoor activities."],correctAnswer:0,explanation:"The opening paragraph identifies heat, limited shade, and low use."},
{id:3,type:"reading",skill:"Detail",question:"Why did the gardener warn against some large trees?",options:["Their leaves would make the courtyard too dark.","Their branches would block the classroom windows.","Their roots might damage drains near the planting area.","Their trunks would prevent benches from being moved."],correctAnswer:2,explanation:"The gardener specifically warned that large roots could damage drains."},
{id:4,type:"reading",skill:"Inference",question:"Why did the students measure temperatures in several locations?",options:["They wanted to decide which class should use the courtyard.","They hoped to prove that every area had the same conditions.","They needed evidence to identify where changes were most necessary.","They planned to compare the courtyard with a nearby playing field."],correctAnswer:2,explanation:"Measuring several areas helped them locate the hottest, least-used space."},
{id:5,type:"reading",skill:"Sequence",question:"Which event happened first?",options:["The students measured the courtyard and interviewed the gardener.","The students installed shade sails above the new benches.","Teachers began using the courtyard for small-group lessons.","A supplier failed to deliver the selected tree species."],correctAnswer:0,explanation:"The investigation came before planning, setbacks, and final use."},
{id:6,type:"reading",skill:"Cause and Effect",question:"Why did the students choose another tree species?",options:["The original trees had already grown too tall.","The selected trees could not be delivered by the supplier.","The principal requested fruit trees instead of shade trees.","The gardener decided that no trees should be planted."],correctAnswer:1,explanation:"A delivery problem forced the team to choose another suitable species."},
{id:7,type:"reading",skill:"Author's Purpose",question:"Why does the author mention the damaged pallet?",options:["To show that the project faced more than one practical setback.","To suggest that all recycled materials are unsafe for schools.","To explain why the project became much more expensive.","To prove that the benches were never completed."],correctAnswer:0,explanation:"The pallet is one example of a setback the team had to manage."},
{id:8,type:"reading",skill:"Problem and Solution",question:"How did the team provide shade while the trees were still young?",options:["They moved the benches under the classroom verandah.","They planted additional trees around every side of the school.","They painted the benches with a darker outdoor coating.","They installed temporary fabric shade sails above the area."],correctAnswer:3,explanation:"The sails supplied temporary shade while the trees matured."},
{id:9,type:"reading",skill:"Vocabulary in Context",question:"What does “adjusted” most nearly mean in paragraph four?",options:["Changed to suit new conditions.","Measured with special equipment.","Removed from the original plan.","Approved by the school principal."],correctAnswer:0,explanation:"They changed the schedule and materials to match new conditions."},
{id:10,type:"reading",skill:"Evidence",question:"Which detail best shows that the courtyard became more useful?",options:["Students used it for reading, games, conversation, and lessons.","The students compared prices before presenting their proposal.","One supplier could not deliver the first choice of trees.","The concrete was painted with a pale outdoor coating."],correctAnswer:0,explanation:"The range of activities shows that more people could use the space."},
{id:11,type:"reading",skill:"Theme",question:"Which lesson is best supported by the passage?",options:["A project succeeds only when the first plan remains unchanged.","Outdoor spaces are more important than indoor classrooms.","Research and flexibility can improve a practical solution.","School problems should always be handled by adults alone."],correctAnswer:2,explanation:"The class gathered evidence, consulted experts, and adapted its plan."},
{id:12,type:"reading",skill:"Text Structure",question:"How is the passage mainly organised?",options:["As instructions for building benches from wooden pallets.","As a comparison between two different school courtyards.","As a description of several unrelated gardening activities.","As a problem, investigation, plan, setbacks, and results."],correctAnswer:3,explanation:"The passage moves through the stages of solving the courtyard problem."},
{id:13,type:"reading",skill:"Inference",question:"What can the reader infer about the students?",options:["They were willing to revise their ideas when difficulties arose.","They believed temperature measurements were unnecessary.","They wanted the gardener to complete every task alone.","They expected the trees to provide full shade immediately."],correctAnswer:0,explanation:"Their responses to delays and shortages show flexibility."},
{id:14,type:"reading",skill:"Reference",question:"In the final paragraph, what does “Their work” refer to?",options:["The teachers' small-group lessons.","The Grade 5 students' courtyard project.","The gardener's routine maintenance.","The supplier's delivery arrangements."],correctAnswer:1,explanation:"The phrase refers to the students' project described throughout the passage."},
{id:15,type:"reading",skill:"Summary",question:"Which sentence best summarises the passage?",options:["A class researched a hot courtyard, adapted its plan, and created a more useful space.","A gardener planted several large trees without consulting the school.","Students painted the entire school and replaced all outdoor furniture.","Parents built a covered hall after the courtyard project failed."],correctAnswer:0,explanation:"This choice includes the problem, process, and outcome."},
{id:16,type:"vocabulary",skill:"Synonym",question:"Which word is closest in meaning to “proposal”?",options:["argument","schedule","measurement","plan"],correctAnswer:3,explanation:"A proposal is a plan or suggestion presented for consideration."},
{id:17,type:"vocabulary",skill:"Antonym",question:"Which word is the best antonym for “temporary”?",options:["permanent","movable","shaded","careful"],correctAnswer:0,explanation:"Permanent means lasting rather than temporary."},
{id:18,type:"vocabulary",skill:"Context Clues",question:"The coating “absorbed less heat.” What does absorbed mean here?",options:["Reflected all available light.","Took in heat from its surroundings.","Removed paint from the concrete.","Spread water across the surface."],correctAnswer:1,explanation:"Absorbed means took in."},
{id:19,type:"vocabulary",skill:"Multiple Meaning",question:"Which sentence uses “shade” as a noun?",options:["Please shade the circle carefully.","The curtains shade the room.","We rested in the shade of the tree.","Clouds shade the playground at noon."],correctAnswer:2,explanation:"In this sentence, shade names an area protected from direct sunlight."},
{id:20,type:"vocabulary",skill:"Prefix",question:"What does the prefix “re-” mean in “replacement”?",options:["before","under","without","again"],correctAnswer:3,explanation:"Replacement involves putting something in place again or instead."},
{id:21,type:"vocabulary",skill:"Suffix",question:"Which word names a person who gardens?",options:["gardener","garden","gardening","gardened"],correctAnswer:0,explanation:"The suffix -er identifies a person who performs an action."},
{id:22,type:"vocabulary",skill:"Connotation",question:"Which word has the most positive connotation?",options:["stubborn","determined","pushy","restless"],correctAnswer:1,explanation:"Determined suggests admirable persistence."},
{id:23,type:"vocabulary",skill:"Idiom",question:"What does “think on your feet” mean?",options:["Stand while completing a task.","Walk while solving a problem.","Respond quickly and sensibly.","Measure distance without tools."],correctAnswer:2,explanation:"The idiom means to react quickly and effectively."},
{id:24,type:"vocabulary",skill:"Word Relationship",question:"Tree is to branch as plant is to ____.",options:["bench","drain","shade","stem"],correctAnswer:3,explanation:"A branch is part of a tree; a stem is part of a plant."},
{id:25,type:"vocabulary",skill:"Figurative Language",question:"Which sentence contains personification?",options:["The tired courtyard waited for its transformation.","The courtyard had two benches near the fence.","Students measured the concrete at midday.","Shade sails covered part of the sitting area."],correctAnswer:0,explanation:"The courtyard is given the human action of waiting."},
{id:26,type:"grammar",skill:"Subject-Verb Agreement",question:"Choose the correct sentence.",options:["The students measures the temperature daily.","The students measure the temperature daily.","The students is measuring the temperature daily.","The students has measured the temperature daily."],correctAnswer:1,explanation:"The plural subject students takes the verb measure."},
{id:27,type:"grammar",skill:"Verb Tense",question:"Which sentence is correctly written in the past tense?",options:["The team changes the schedule yesterday.","The team will change the schedule yesterday.","The team changed the schedule yesterday.","The team changing the schedule yesterday."],correctAnswer:2,explanation:"Changed is the correct past-tense verb."},
{id:28,type:"grammar",skill:"Pronouns",question:"Choose the correct pronoun: “Mrs. Morgan praised the students because ___ had worked carefully.”",options:["her","him","it","they"],correctAnswer:3,explanation:"They refers to the plural noun students."},
{id:29,type:"grammar",skill:"Capitalisation",question:"Which sentence is capitalised correctly?",options:["Seaview Primary began the Cool Courtyard Project in May.","seaview primary began the cool courtyard project in May.","Seaview primary began the Cool courtyard Project in may.","seaview Primary began the Cool Courtyard project in May."],correctAnswer:0,explanation:"The school name, project title, and month require capital letters."},
{id:30,type:"grammar",skill:"Punctuation",question:"Which sentence uses commas correctly?",options:["The plan included trees benches and shade sails.","The plan included trees, benches, and shade sails.","The plan, included trees benches, and shade sails.","The plan included, trees, benches and shade sails."],correctAnswer:1,explanation:"Commas correctly separate the items in the series."},
{id:31,type:"grammar",skill:"Conjunctions",question:"Choose the best conjunction: “The rain delayed the painting, ___ the team changed the schedule.”",options:["although","unless","so","while"],correctAnswer:2,explanation:"So introduces the result of the delay."},
{id:32,type:"grammar",skill:"Possessive Nouns",question:"Which sentence correctly shows that the benches belong to the school?",options:["The schools benches were movable.","The schools' benches were movable.","The school benches' were movable.","The school's benches were movable."],correctAnswer:3,explanation:"School's is the singular possessive form."},
{id:33,type:"grammar",skill:"Complete Sentences",question:"Which group of words is a complete sentence?",options:["The students presented their proposal clearly.","Because the students presented their proposal.","Near the newly painted section of concrete.","Preparing charts for the parent-teacher association."],correctAnswer:0,explanation:"It has a subject, predicate, and complete thought."},
{id:34,type:"grammar",skill:"Adjectives",question:"Which word is the adjective in “The pale coating reduced the heat”?",options:["coating","pale","reduced","heat"],correctAnswer:1,explanation:"Pale describes the noun coating."},
{id:35,type:"grammar",skill:"Sentence Combining",question:"Which sentence best combines these ideas? “The trees were young. Shade sails were installed.”",options:["The trees were young, shade sails were installed.","The trees were young and because.","Because the trees were young, shade sails were installed.","Shade sails were installed, because young."],correctAnswer:2,explanation:"This sentence clearly shows the cause-and-effect relationship."},
{id:36,type:"writing",skill:"Topic Sentence",question:"Which is the strongest topic sentence for a paragraph about improving school spaces?",options:["Schools can improve shared spaces through careful planning and teamwork.","Some schools have walls, doors, and windows.","Students sometimes sit outside during lunch.","Concrete surfaces can be painted many colours."],correctAnswer:0,explanation:"It clearly introduces a broad controlling idea."},
{id:37,type:"writing",skill:"Supporting Detail",question:"Which detail best supports the statement “The project increased use of the courtyard”?",options:["Students began reading, playing games, and learning in the area.","The class compared the prices of several materials.","One pallet was too damaged to become a bench.","The selected trees were unavailable from the first supplier."],correctAnswer:0,explanation:"The new activities directly show increased use."},
{id:38,type:"writing",skill:"Transitions",question:"Choose the best transition: “The supplier could not deliver the trees. ___, the class selected another species.”",options:["For example","Therefore","Meanwhile","Similarly"],correctAnswer:1,explanation:"Therefore introduces the result of the delivery problem."},
{id:39,type:"writing",skill:"Organisation",question:"Which sentence does NOT belong in a paragraph about improving a courtyard?",options:["Plant suitable trees that will provide shade.","Use movable benches to create flexible seating.","The school gardening club also keeps records of plants growing in other parts of the campus.","Choose materials that can withstand outdoor weather."],correctAnswer:2,explanation:"The gardening-club detail is related to the school environment, but it does not describe a change that improves the courtyard, so it breaks the paragraph’s focus."},
{id:40,type:"writing",skill:"Conclusion",question:"Which is the strongest conclusion for an essay about solving school problems?",options:["The courtyard project shows that pupils can make useful improvements when they investigate a problem carefully.","Improving a school space often requires several smaller changes rather than one large solution.","School improvement projects work best when students are willing to adjust their plans when difficulties arise.","When students investigate carefully and adapt wisely, they can create lasting improvements."],correctAnswer:3,explanation:"The keyed conclusion captures the whole project lesson by combining careful investigation, adaptation when difficulties arose, and lasting improvement."}
]

const sectionLabel = (type: QuestionType) => type === "reading" ? "Reading Comprehension" : type === "vocabulary" ? "Vocabulary & Word Study" : type === "grammar" ? "Grammar & Language Use" : "Writing Skills"

export default function G5LaMix8MockTest() {
  const { isPremium, user } = useAuth()
  const sourceQuestions = isPremium ? QUESTIONS : QUESTIONS.slice(0, FREE_QUESTION_LIMIT)
  const [started, setStarted] = useState(false)
  const [showResults, setShowResults] = useState(false)
  const [questions, setQuestions] = useState<Question[]>([])
  const [answers, setAnswers] = useState<(number | null)[]>([])
  const [currentQuestion, setCurrentQuestion] = useState(0)
  const [timeLeft, setTimeLeft] = useState(3600)
  const hasSavedResult = useRef(false)
  const availableQuestions = questions.length ? questions : sourceQuestions
  const totalQuestions = availableQuestions.length
  const calculateScore = useCallback(() => answers.reduce((score, answer, index) => score + (answer === availableQuestions[index]?.correctAnswer ? 1 : 0), 0), [answers, availableQuestions])
  const percentage = useCallback(() => totalQuestions ? Math.round((calculateScore() / totalQuestions) * 100) : 0, [calculateScore, totalQuestions])

  useEffect(() => { if (!started || showResults) return; const timer = setInterval(() => setTimeLeft((previous) => { if (previous <= 1) { setShowResults(true); return 0 } return previous - 1 }), 1000); return () => clearInterval(timer) }, [started, showResults])
  useEffect(() => { if (!showResults || !user?.id || hasSavedResult.current || !availableQuestions.length) return; hasSavedResult.current = true; void saveStudentTestResult({ parentId:user.id, studentName:user.childName ?? "Student", grade:"grade5", subject:"Literacy", testName:"Mixed 8", difficulty:"Mixed", score:calculateScore(), totalQuestions, percentage:percentage(), completedAt:new Date().toISOString() }).catch(() => { hasSavedResult.current = false }) }, [showResults, user?.id, user?.childName, availableQuestions.length, calculateScore, percentage, totalQuestions])

  const startTest = () => { const prepared = isPremium ? prepareAssessment(QUESTIONS) : preparePreview(QUESTIONS, FREE_QUESTION_LIMIT); setQuestions(prepared); setAnswers(new Array(prepared.length).fill(null)); setCurrentQuestion(0); setTimeLeft(3600); setShowResults(false); hasSavedResult.current = false; setStarted(true) }
  const resetTest = () => { setStarted(false); setShowResults(false); setQuestions([]); setAnswers([]); setCurrentQuestion(0); setTimeLeft(3600); hasSavedResult.current = false }

  if (!started) return <div className="min-h-screen bg-gradient-to-b from-sky-50 to-slate-50"><Header/><main className="container mx-auto px-4 py-10"><Link href="/mock-tests/language-arts"><Button variant="ghost" className="mb-6"><ArrowLeft className="mr-2 h-4 w-4"/>Back to Language Arts Mock Tests</Button></Link><Card className="mx-auto max-w-3xl border-blue-200 shadow-lg"><CardHeader className="bg-blue-50 text-center"><BookOpen className="mx-auto mb-4 h-14 w-14 text-blue-600"/><CardTitle className="text-2xl text-blue-800">Language Arts Mixed 8</CardTitle><p className="text-slate-600">Grade 5 PEP Language Arts · Mixed Level Practice</p></CardHeader><CardContent className="space-y-6 p-6">{!isPremium&&<div className="rounded-lg border border-amber-200 bg-amber-50 p-4"><div className="flex items-start gap-3"><Lock className="mt-1 h-5 w-5 text-amber-600"/><div><p className="font-semibold text-amber-800">Free Preview Mode</p><p className="text-sm text-amber-700">Try {FREE_QUESTION_LIMIT} questions free. Upgrade to unlock all 40.</p><Link href="/pricing" className="mt-3 inline-block"><Button className="bg-amber-500 hover:bg-amber-600"><Crown className="mr-2 h-4 w-4"/>Upgrade to Premium</Button></Link></div></div></div>}<div className="rounded-lg border border-blue-200 bg-white p-4"><h3 className="mb-2 font-semibold text-slate-800">Mixed Level Overview</h3><p className="text-slate-700">This test blends easy, moderate, and challenging questions across reading, vocabulary, grammar, and writing, using the Cool Courtyard Project as its central reading passage.</p></div><div className="rounded-lg bg-sky-50 p-4"><h3 className="mb-2 font-semibold text-sky-800">What to Expect</h3><ul className="space-y-1 text-sm text-slate-700"><li>Reading: literal comprehension → inference → text analysis</li><li>Vocabulary: meaning in context → word study → figurative language</li><li>Grammar: agreement → punctuation → sentence construction</li><li>Writing: topic sentences → evidence → organisation and conclusions</li></ul></div><div className="grid grid-cols-2 gap-4 text-center"><div className="rounded-lg bg-gray-50 p-4"><p className="text-2xl font-bold text-blue-600">{totalQuestions}</p><p className="text-sm text-slate-600">Questions {!isPremium&&"(Preview)"}</p></div><div className="rounded-lg bg-gray-50 p-4"><p className="text-2xl font-bold text-blue-600">60</p><p className="text-sm text-slate-600">Minutes</p></div></div><Button onClick={startTest} className="w-full bg-blue-600 py-6 text-lg hover:bg-blue-700">Start Test</Button></CardContent></Card></main><Footer/></div>

  if (showResults) { const score = calculateScore(), pct = percentage(); return <div className="min-h-screen bg-gradient-to-b from-sky-50 to-slate-50"><Header/><main className="container mx-auto px-4 py-10"><Card className="mx-auto max-w-4xl border-blue-200 shadow-lg"><CardHeader className="bg-blue-50 text-center"><CheckCircle className="mx-auto mb-4 h-14 w-14 text-blue-600"/><CardTitle className="text-2xl text-blue-800">Mixed 8 Results</CardTitle><p className="text-5xl font-bold text-blue-600">{pct}%</p><p className="text-slate-600">{score} of {totalQuestions} correct</p></CardHeader><CardContent className="space-y-4 p-6">{availableQuestions.map((question,index)=>{const correct=answers[index]===question.correctAnswer;return <div key={question.id} className={`rounded-lg border-l-4 p-4 ${correct?"border-green-500 bg-green-50":"border-red-500 bg-red-50"}`}><p className="font-semibold">{correct?"✓":"✗"} Question {index+1}: {question.question}</p><p className="text-sm">Your answer: {answers[index]===null?"Not answered":question.options[answers[index]!]}</p>{!correct&&<p className="text-sm text-green-700">Correct answer: {question.options[question.correctAnswer]}</p>}<p className="text-sm text-slate-600">{question.explanation}</p></div>})}<div className="flex flex-wrap gap-3"><Button onClick={resetTest}><RotateCcw className="mr-2 h-4 w-4"/>Try Again</Button><Button variant="outline" onClick={()=>window.print()}><Printer className="mr-2 h-4 w-4"/>Print Results</Button><Link href="/mock-tests/language-arts"><Button variant="outline"><Home className="mr-2 h-4 w-4"/>More Tests</Button></Link></div></CardContent></Card></main><Footer/></div> }

  const question=availableQuestions[currentQuestion], formatTime=`${String(Math.floor(timeLeft/60)).padStart(2,"0")}:${String(timeLeft%60).padStart(2,"0")}`
  return <div className="min-h-screen bg-gradient-to-b from-sky-50 to-slate-50"><Header/><header className="sticky top-0 z-10 bg-blue-800 text-white"><div className="container mx-auto flex items-center justify-between px-4 py-4"><div><h1 className="font-bold">Language Arts Mixed 8</h1><p className="text-xs text-blue-100">Question {currentQuestion+1} of {totalQuestions}</p></div><div className="flex items-center gap-2 rounded-lg bg-green-600 px-4 py-2 font-mono"><Clock className="h-5 w-5"/>{formatTime}</div></div></header><main className="container mx-auto max-w-5xl px-4 py-6"><Progress value={((currentQuestion+1)/totalQuestions)*100} className="mb-4"/><Card><CardContent className="space-y-5 p-6">{question.type==="reading"&&<div className="max-h-80 overflow-y-auto whitespace-pre-line rounded border bg-slate-50 p-4 text-sm">{PASSAGE}</div>}<div><p className="text-sm font-semibold text-blue-700">{sectionLabel(question.type)} · {question.skill}</p><h2 className="mt-2 text-lg font-medium">{question.question}</h2></div><div className="space-y-3">{question.options.map((option,index)=><button key={option} onClick={()=>setAnswers((previous)=>previous.map((value,answerIndex)=>answerIndex===currentQuestion?index:value))} className={`flex w-full gap-3 rounded-lg border-2 p-4 text-left transition ${answers[currentQuestion]===index?"border-blue-600 bg-blue-50":"border-gray-200 bg-white hover:border-blue-300"}`}><span className="font-medium text-blue-700">{String.fromCharCode(65+index)}.</span><span>{option}</span></button>)}</div><div className="flex justify-between"><Button variant="outline" disabled={currentQuestion===0} onClick={()=>setCurrentQuestion((value)=>value-1)}>Previous</Button>{currentQuestion===totalQuestions-1?<Button onClick={()=>setShowResults(true)} className="bg-green-600 hover:bg-green-700"><Flag className="mr-2 h-4 w-4"/>Submit Test</Button>:<Button onClick={()=>setCurrentQuestion((value)=>value+1)}>Next</Button>}</div></CardContent></Card></main><Footer/></div>
}
