"use client";
import{useEffect,useMemo,useRef,useState}from"react";
import Link from"next/link";
import{Header}from"@/components/header";
import{Footer}from"@/components/footer";
import{Button}from"@/components/ui/button";
import{Card,CardContent,CardHeader,CardTitle}from"@/components/ui/card";
import{Progress}from"@/components/ui/progress";
import{useAuth}from"@/contexts/auth-context";
import{saveStudentTestResult}from"@/lib/student-test-results";
const P="For years, residents of Bellview depended on a small library housed in two rooms beside the community centre. The shelves were crowded, and many children who lived in the surrounding hills could not visit regularly because transportation was costly. When the library’s roof began leaking, some residents feared that the service would close altogether.\n\nMrs. Campbell, the librarian, proposed a different solution. Instead of waiting until a new building could be funded, she suggested converting an unused minibus into a travelling library. The idea sounded ambitious, but she presented a careful plan. The bus would visit four communities each week, carry books for different age groups, and include a small solar panel to power lights and two tablets.\n\nThe citizens’ association agreed to lead a fundraising drive. A mechanic offered to inspect the bus, local artists volunteered to paint it, and secondary-school students collected gently used books. Not every donation was useful. Some books were badly damaged or far beyond the reading level of the children, so volunteers sorted each item before placing it on the shelves.\n\nAfter three months of work, the Bellview Book Bus made its first journey. At the first stop, children lined up before the doors opened. They borrowed storybooks, used the tablets to research homework, and listened as Mrs. Campbell read aloud. Adults also came to complete online forms and ask for help writing job applications.\n\nThe project soon faced a problem. During heavy rain, the narrow road to Cedar Hill became unsafe. Rather than cancel the service permanently, the organisers changed the schedule and arranged a collection point at the foot of the hill. A shopkeeper kept a locked box where reserved books could be collected and returned.\n\nBy the end of the school year, library membership had more than doubled. The Book Bus had not replaced the need for a permanent library, but it had shown what a community could accomplish by using the resources already available. More importantly, it brought books, technology, and practical assistance closer to people who had previously been left out.";
type T="reading"|"vocabulary"|"grammar"|"writing";
type Q={id:number,type:T,skill:string,question:string,options:string[],correctAnswer:number,explanation:string};
const R=[
[1,"reading","Main Idea","What is the passage mainly about?",["A community adapted an unused bus to extend library services.","A librarian replaced all printed books with digital devices.","Residents repaired a damaged roof at the community centre.","Children organised transport to visit a distant public library."],0,"The passage traces how Bellview created and operated a travelling library."],
[2,"reading","Problem and Solution","Which problem most directly led to Mrs. Campbell’s proposal?",["The bus route had become unreliable during the school year.","The library was crowded, leaking, and hard for some children to reach.","Volunteers had collected too many books for the available shelves.","Adults needed a quieter place to complete online applications."],1,"The first paragraph identifies limited space, a leaking roof, and difficult access."],
[3,"reading","Detail","What was the solar panel intended to do?",["Charge the bus battery during long journeys.","Keep the shelves dry during heavy rainfall.","Supply power for lights and two tablets.","Send a signal when the bus reached each stop."],2,"The plan specifically says the panel would power lights and two tablets."],
[4,"reading","Inference","Why did Mrs. Campbell present a careful plan?",["She wanted to prove that the permanent library was unnecessary.","She hoped to prevent residents from changing the bus route.","She needed permission to sell donated books for repairs.","She wanted others to see that the ambitious idea was practical."],3,"A detailed plan would make the proposal credible and easier to support."],
[5,"reading","Sequence","Which event happened first?",["Mrs. Campbell proposed converting an unused minibus.","Children borrowed books during the first journey.","A shopkeeper stored reserved books in a locked box.","Library membership more than doubled by year’s end."],0,"The proposal came before fundraising, launch, adjustments, and growth."],
[6,"reading","Cause and Effect","Why were some donated books not placed on the bus?",["The artists needed them while designing the bus exterior.","Some were damaged or unsuitable for the children’s reading levels.","The mechanic asked that the shelves remain empty during inspection.","The association planned to exchange them for electronic tablets."],1,"Volunteers rejected books that were damaged or far above the children’s levels."],
[7,"reading","Author’s Purpose","Why does the author mention adults using the bus?",["To show that adults borrowed more storybooks than children.","To explain why the tablets were removed from the service.","To show that the project supported several community needs.","To suggest that children should use the bus less often."],2,"The adult services demonstrate that the bus offered more than children’s reading materials."],
[8,"reading","Problem and Solution","How did organisers respond when the Cedar Hill road became unsafe?",["They stopped serving Cedar Hill until a permanent library opened.","They asked children to walk down the hill during heavy rain.","They moved all library services to the shopkeeper’s building.","They changed the schedule and created a collection point below the hill."],3,"They adapted the service rather than cancelling it."],
[9,"reading","Vocabulary in Context","What does “ambitious” most nearly mean in paragraph two?",["Difficult but worth attempting.","Cheap and simple to complete.","Secret and likely to cause trouble.","Ordinary and already widely used."],0,"The proposal required significant effort but was presented as achievable."],
[10,"reading","Evidence","Which detail best shows that the Book Bus was successful?",["Artists volunteered to paint the outside of the bus.","Library membership had more than doubled by the end of the year.","Some donated books were removed before shelving.","The road to Cedar Hill became unsafe during heavy rain."],1,"The increase in membership is direct evidence of expanded use."],
[11,"reading","Theme","Which lesson is best supported by the passage?",["Permanent buildings are less useful than mobile services.","Technology is more valuable than printed books.","Cooperation and flexibility can help a community solve problems.","Fundraising is the only way to improve public services."],2,"The community combined skills and adapted when difficulties arose."],
[12,"reading","Text Structure","How is the passage mainly organised?",["As a comparison between two competing library plans.","As instructions for converting a bus into a library.","As a description of several unrelated community services.","As a problem, a proposed solution, its challenges, and its results."],3,"The text moves from the original problem through implementation and outcomes."],
[13,"reading","Inference","What can the reader infer about the organisers?",["They were willing to revise the plan when conditions changed.","They believed only children should use library services.","They expected the bus to replace the permanent library completely.","They preferred cancelling routes rather than using collection points."],0,"Their response to Cedar Hill shows practical flexibility."],
[14,"reading","Reference","In the final paragraph, what does “it” refer to in “it brought books, technology…”?",["The citizens’ association.","The Bellview Book Bus.","The permanent library building.","The Cedar Hill collection box."],1,"The pronoun refers to the Book Bus discussed immediately before it."],
[15,"reading","Summary","Which sentence best summarises the passage?",["A damaged community library closed after residents failed to repair it.","Volunteers collected books, but unsafe roads ended the project early.","Bellview residents created a mobile library, adapted it to challenges, and expanded access.","A librarian bought tablets so adults could complete forms at the centre."],2,"This choice includes the project, its adaptation, and its result without irrelevant detail."],
[16,"vocabulary","Synonym","Which word is closest in meaning to “reserved” in “reserved books”?",["Damaged","Painted","Borrowed","Requested"],3,"Reserved books are books requested and set aside."],
[17,"vocabulary","Antonym","Which word is the best antonym for “permanent”?",["Temporary","Crowded","Practical","Available"],0,"Temporary means lasting for a limited time."],
[18,"vocabulary","Context Clues","The volunteers “sorted” the donations. What did they do?",["Sold every book immediately.","Grouped and checked the books carefully.","Packed the books without examining them.","Read each book aloud to the children."],1,"The next sentence explains that they checked suitability before shelving."],
[19,"vocabulary","Multiple Meaning","Which sentence uses “light” in the same way as “power lights”?",["The bag was light enough to carry.","A light rain fell before noon.","The light above the desk helped her read.","His light remark made everyone laugh."],2,"Here light means a device that provides illumination."],
[20,"vocabulary","Prefix","What does the prefix “un-” mean in “unused”?",["Again","Before","Together","Not"],3,"Unused means not used."],
[21,"vocabulary","Suffix","Which word means “a person who works in a library”?",["Librarian","Library","Literate","Liberally"],0,"The suffix -arian can identify a person connected with a field or place."],
[22,"vocabulary","Connotation","Which word has the most positive connotation?",["Stubborn","Persistent","Pushy","Restless"],1,"Persistent suggests admirable determination."],
[23,"vocabulary","Idiom","What does “lend a hand” mean?",["Give someone a glove.","Borrow an object.","Offer help with a task.","Wave to attract attention."],2,"The idiom means to help."],
[24,"vocabulary","Word Relationship","Book is to library as painting is to ____.",["Mechanic","Tablet","Journey","Gallery"],3,"A gallery is a place where paintings are displayed."],
[25,"vocabulary","Figurative Language","Which sentence contains personification?",["The tired bus climbed the hill reluctantly.","The bus travelled slowly up the hill.","The bus carried books in wooden shelves.","The bus stopped beside the community shop."],0,"The bus is given the human quality of reluctance."],
[26,"grammar","Subject-Verb Agreement","Choose the correct sentence.",["The volunteers sorts the books each week.","The volunteers sort the books each week.","The volunteers is sorting the books each week.","The volunteers has sorted the books each week."],1,"Plural subject volunteers takes the plural verb sort."],
[27,"grammar","Verb Tense","Which sentence is written correctly in the past tense?",["The bus visits Cedar Hill yesterday.","The bus will visit Cedar Hill yesterday.","The bus visited Cedar Hill yesterday.","The bus visiting Cedar Hill yesterday."],2,"Visited correctly matches the past-time clue yesterday."],
[28,"grammar","Pronouns","Choose the correct pronoun: “Mrs. Campbell thanked the artists because ___ had painted the bus.”",["her","him","it","they"],3,"They refers to the plural noun artists."],
[29,"grammar","Capitalisation","Which sentence is capitalised correctly?",["The Bellview Book Bus visited Cedar Hill on Friday.","The bellview book bus visited cedar hill on Friday.","The Bellview book bus visited Cedar hill on friday.","The bellview Book Bus visited Cedar Hill on Friday."],0,"Proper names and Friday require capitals."],
[30,"grammar","Punctuation","Which sentence uses commas correctly?",["The bus carried books tablets and forms.","The bus carried books, tablets, and forms.","The bus, carried books tablets, and forms.","The bus carried, books, tablets and forms."],1,"Commas separate items in a series."],
[31,"grammar","Conjunctions","Choose the best conjunction: “The road was unsafe, ___ the organisers changed the schedule.”",["although","unless","so","while"],2,"So shows the result of the unsafe road."],
[32,"grammar","Possessive Nouns","Which sentence correctly shows that the bus belongs to the community?",["The communitys bus was newly painted.","The communities bus was newly painted.","The communitys’ bus was newly painted.","The community’s bus was newly painted."],3,"Community’s is the singular possessive form."],
[33,"grammar","Complete Sentences","Which group of words is a complete sentence?",["The children waited beside the bus.","While the children waited.","Beside the newly painted bus.","Waiting for the doors to open."],0,"It has a subject, predicate, and complete thought."],
[34,"grammar","Adjectives","Which word is the adjective in “The narrow road became unsafe”?",["road","narrow","became","unsafe"],1,"Narrow describes the noun road."],
[35,"grammar","Sentence Combining","Which sentence best combines these ideas? “The rain was heavy. The route was changed.”",["The rain was heavy, the route was changed.","The rain was heavy and because.","Because the rain was heavy, the route was changed.","The route was changed, because heavy."],2,"This correctly shows the cause-and-effect relationship."],
[36,"writing","Topic Sentence","Which is the strongest topic sentence for a paragraph about mobile libraries?",["Some buses are painted bright colours.","Books can be placed on several kinds of shelves.","Many communities have roads that become wet.","Mobile libraries can bring learning resources to people who live far from buildings."],3,"It clearly introduces a broad idea suitable for development."],
[37,"writing","Supporting Detail","Which detail best supports the statement “The Book Bus served more than one purpose”?",["Children borrowed books while adults received help with forms and job applications.","The bus had doors, seats, shelves, and several painted panels.","Volunteers worked for three months before the first journey.","The library roof leaked beside the community centre."],0,"It gives two distinct ways the service helped residents."],
[38,"writing","Transitions","Choose the best transition: “The road became unsafe. ___, the organisers created a collection point.”",["For example","Therefore","Meanwhile","Similarly"],1,"Therefore introduces a result."],
[39,"writing","Organisation","Which sentence does NOT belong in a paragraph about preparing the Book Bus?",["A mechanic inspected the vehicle before it travelled.","Artists painted the outside of the bus.","Bananas grow well in warm tropical climates.","Volunteers sorted books before shelving them."],2,"The banana sentence is unrelated to preparing the bus."],
[40,"writing","Conclusion","Which is the strongest conclusion for an essay about community cooperation?",["That is all I know about people working together.","Communities have many people and many different jobs.","Some projects are easier than others to complete.","When people combine their skills and adapt to challenges, they can create lasting improvements."],3,"It restates the central idea and leaves a meaningful final thought."]
];
const ALL:Q[]=R.map((r:any)=>({id:r[0],type:r[1],skill:r[2],question:r[3],options:r[4],correctAnswer:r[5],explanation:r[6]}));
const mix=<T,>(a:T[])=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const prep=(a:Q[])=>mix(a).map(q=>{const o=mix(q.options.map((v,i)=>({v,i})));return{...q,options:o.map(x=>x.v),correctAnswer:o.findIndex(x=>x.i===q.correctAnswer)}});
const label=(t:T)=>t==="reading"?"Reading Comprehension":t==="vocabulary"?"Vocabulary & Word Study":t==="grammar"?"Grammar & Language Use":"Writing Skills";
export default function G5LaMix6MockTest(){
 const{isPremium,user}=useAuth();const[started,setStarted]=useState(false),[done,setDone]=useState(false),[qs,setQs]=useState<Q[]>([]),[ans,setAns]=useState<(number|null)[]>([]),[at,setAt]=useState(0),[left,setLeft]=useState(3600);const saved=useRef(false);
 const src=useMemo(()=>isPremium?ALL:ALL.slice(0,5),[isPremium]),score=()=>ans.reduce((s,a,i)=>s+(a===qs[i]?.correctAnswer?1:0),0),pct=()=>qs.length?Math.round(score()*100/qs.length):0;
 useEffect(()=>{if(!started||done)return;const t=setInterval(()=>setLeft(x=>{if(x<=1){setDone(true);return 0}return x-1}),1000);return()=>clearInterval(t)},[started,done]);
 useEffect(()=>{if(!done||!user?.id||saved.current||!qs.length)return;saved.current=true;void saveStudentTestResult({parentId:user.id,studentName:user.childName??"Student",grade:"grade5",subject:"Literacy",testName:"Mixed 6",difficulty:"Mixed",score:score(),totalQuestions:qs.length,percentage:pct(),completedAt:new Date().toISOString()}).catch(()=>{saved.current=false})},[done,user?.id,user?.childName,qs,ans]);
 const start=()=>{const x=prep(src);setQs(x);setAns(Array(x.length).fill(null));setAt(0);setLeft(3600);setDone(false);saved.current=false;setStarted(true)},reset=()=>{setStarted(false);setDone(false);setQs([]);setAns([]);setAt(0);setLeft(3600);saved.current=false};
 if(!started)return <div className="min-h-screen bg-slate-50"><Header/><main className="container mx-auto px-4 py-10"><Card className="mx-auto max-w-3xl"><CardHeader className="text-center"><CardTitle>Language Arts Mixed 6</CardTitle><p>Grade 5 PEP · 40-question mixed practice</p></CardHeader><CardContent className="space-y-5">{!isPremium&&<div className="rounded border border-amber-300 bg-amber-50 p-4">Free preview: 5 questions. Premium unlocks all 40.</div>}<div className="rounded border p-4"><b>Revised assessment standard</b><p className="mt-2 text-sm text-slate-600">Choices are similar in length, closely related, and written to prevent guessing by answer length or wording.</p></div><Button className="w-full" onClick={start}>Start Mixed 6</Button></CardContent></Card></main><Footer/></div>;
 if(done)return <div className="min-h-screen bg-slate-50"><Header/><main className="container mx-auto px-4 py-8"><Card className="mx-auto max-w-5xl"><CardHeader className="text-center"><CardTitle>Mixed 6 Results</CardTitle><div className="text-5xl font-bold text-blue-600">{pct()}%</div><p>{score()} of {qs.length} correct</p></CardHeader><CardContent className="space-y-4">{qs.map((q,i)=>{const ok=ans[i]===q.correctAnswer;return <div key={q.id} className={`rounded border-l-4 p-4 ${ok?"border-green-500 bg-green-50":"border-red-500 bg-red-50"}`}><b>{ok?"✓":"✗"} Question {i+1}: {q.question}</b><p className="text-sm">Your answer: {ans[i]===null?"Not answered":q.options[ans[i]!]}</p>{!ok&&<p className="text-sm text-green-700">Correct answer: {q.options[q.correctAnswer]}</p>}<p className="text-sm text-slate-600">{q.explanation}</p></div>})}<div className="flex gap-3"><Button onClick={reset}>Try Again</Button><Button variant="outline" onClick={()=>window.print()}>Print Results</Button><Link href="/mock-tests/language-arts"><Button variant="outline">More Tests</Button></Link></div></CardContent></Card></main><Footer/></div>;
 const q=qs[at];return <div className="min-h-screen bg-slate-50"><Header/><main className="container mx-auto max-w-5xl px-4 py-6"><div className="mb-3 flex justify-between rounded bg-white p-4"><b>Mixed 6 · Question {at+1} of {qs.length}</b><b>{String(Math.floor(left/60)).padStart(2,"0")}:{String(left%60).padStart(2,"0")}</b></div><Progress value={(at+1)*100/qs.length}/><Card className="mt-4"><CardContent className="space-y-5 p-6">{q.type==="reading"&&<div className="max-h-80 overflow-y-auto whitespace-pre-line rounded border bg-slate-50 p-4 text-sm">{P}</div>}<div><span className="text-sm text-blue-700">{label(q.type)} · {q.skill}</span><h2 className="mt-2 text-lg font-medium">{q.question}</h2></div><div className="space-y-3">{q.options.map((o,i)=><button key={o} onClick={()=>setAns(a=>a.map((v,k)=>k===at?i:v))} className={`flex w-full gap-3 rounded border p-4 text-left ${ans[at]===i?"border-blue-500 bg-blue-50":"bg-white"}`}><span>{String.fromCharCode(65+i)}.</span><span>{o}</span></button>)}</div><div className="flex justify-between"><Button variant="outline" disabled={at===0} onClick={()=>setAt(at-1)}>Previous</Button>{at===qs.length-1?<Button onClick={()=>setDone(true)}>Submit Test</Button>:<Button onClick={()=>setAt(at+1)}>Next</Button>}</div></CardContent></Card></main><Footer/></div>
}